"""Combined output formatter for Drupal Aggregator.

This module combines markdown generation and PDF conversion into a single interface.
"""

from html import escape
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import markdown
from bs4 import BeautifulSoup, NavigableString, Tag

from drupal_news.utils.consolidated_utils import get_period_label, safe_write_text


def generate_parsed_md(
    items: List[Dict[str, Any]],
    timeframe_days: int,
    timezone: str,
    max_rows: int = 200,
    period_label: str = None,
) -> str:
    """Generate parsed.md with raw collected data."""
    md_lines = []

    if period_label is None:
        period_label = get_period_label(timeframe_days)

    md_lines.append(f"# Drupal {period_label} - Parsed Data\n")
    md_lines.append(f"**Timeframe:** Last {timeframe_days} days")
    md_lines.append(f"**Timezone:** {timezone}")
    md_lines.append(f"**Total Items:** {len(items)}\n")

    rss_items = [item for item in items if item.get("source_type") == "rss"]
    page_items = [item for item in items if item.get("source_type") == "page"]

    if rss_items:
        md_lines.append("## RSS Feed Items\n")
        md_lines.append("| URL | Title | Description |")
        md_lines.append("|-----|-------|-------------|")

        for item in rss_items[:max_rows]:
            url = item.get("url", "")
            title = item.get("title", "").replace("|", "\\|")
            desc = item.get("description", "").replace("|", "\\|")[:100]
            md_lines.append(f"| {url} | {title} | {desc} |")

        if len(rss_items) > max_rows:
            md_lines.append(f"\n*Showing {max_rows} of {len(rss_items)} items*\n")

    if page_items:
        md_lines.append("\n## Web Page Items\n")
        md_lines.append("| URL | Title | Description |")
        md_lines.append("|-----|-------|-------------|")

        for item in page_items[:max_rows]:
            url = item.get("url", "")
            title = item.get("title", "").replace("|", "\\|")
            desc = item.get("description", "").replace("|", "\\|")[:100]
            md_lines.append(f"| {url} | {title} | {desc} |")

        if len(page_items) > max_rows:
            md_lines.append(f"\n*Showing {max_rows} of {len(page_items)} items*\n")

    md_lines.append("\n## Statistics\n")
    md_lines.append(f"- RSS items: {len(rss_items)}")
    md_lines.append(f"- Page items: {len(page_items)}")
    md_lines.append(f"- Total: {len(items)}")

    return "\n".join(md_lines)


def write_parsed_md(items: List[Dict[str, Any]], output_path: Path, **kwargs):
    """Write parsed.md file."""
    markdown_text = generate_parsed_md(items, **kwargs)
    safe_write_text(markdown_text, output_path)


def generate_summary_md(summary_text: str, metadata: Dict[str, Any]) -> str:
    """Generate summary.md with AI summary and metadata."""
    md_lines = []

    period_label = metadata.get("period_label", "Weekly")
    md_lines.append(f"# Drupal {period_label} Summary\n")

    if metadata.get("date"):
        md_lines.append(f"**Date:** {metadata['date']}")
        md_lines.append("\n")
    if metadata.get("timeframe_days"):
        md_lines.append(f"**Timeframe:** Last {metadata['timeframe_days']} days")
        md_lines.append("\n")
    if metadata.get("timezone"):
        md_lines.append(f"**Timezone:** {metadata['timezone']}")
        md_lines.append("\n")
    if metadata.get("provider"):
        md_lines.append(f"**AI Provider:** {metadata['provider']}")
        md_lines.append("\n")
    if metadata.get("model"):
        md_lines.append(f"**Model:** {metadata['model']}")

    md_lines.append("\n---\n")
    md_lines.append(summary_text)
    md_lines.append("\n---\n")
    md_lines.append("*Generated by Drupal News Aggregator*")
    md_lines.append("\n")
    if metadata.get("generated_at"):
        md_lines.append(f"*Generated at: {metadata['generated_at']}*")

    return "\n".join(md_lines)


def write_summary_md(summary_text: str, output_path: Path, metadata: Dict[str, Any]):
    """Write summary.md file."""
    markdown_text = generate_summary_md(summary_text, metadata)
    safe_write_text(markdown_text, output_path)


def items_to_text(items: List[Dict[str, Any]], max_items: int = 200) -> str:
    """Convert items to plain text format for AI processing."""
    lines = []

    for i, item in enumerate(items[:max_items], 1):
        lines.append(f"{i}. {item.get('title', 'Untitled')}")
        lines.append(f"   URL: {item.get('url', '')}")

        if item.get("description"):
            lines.append(f"   Description: {item['description'][:200]}")

        if item.get("date"):
            lines.append(f"   Date: {item['date']}")

        lines.append("")

    return "\n".join(lines)


def markdown_to_pdf(
    markdown_path: Path,
    pdf_path: Path,
    title: Optional[str] = None,
    css_style: Optional[str] = None,
) -> Tuple[bool, Optional[str]]:
    """Convert markdown file to PDF using ReportLab."""
    _ = css_style

    try:
        from reportlab.lib import colors
        from reportlab.lib.enums import TA_CENTER
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
        from reportlab.lib.units import cm
        from reportlab.platypus import (
            Paragraph,
            Preformatted,
            SimpleDocTemplate,
            Spacer,
            Table,
            TableStyle,
        )
    except ImportError:
        message = "reportlab not installed. Install with: pip install reportlab"
        print(f"Error: {message}")
        return False, message

    try:
        md_content = markdown_path.read_text(encoding="utf-8")
        md = markdown.Markdown(
            extensions=["extra", "codehilite", "tables", "toc", "fenced_code"]
        )
        html_body = md.convert(md_content)
        doc_title = title or "Drupal Aggregator Summary"

        stylesheet = getSampleStyleSheet()
        styles = {
            "title": ParagraphStyle(
                "DrupalTitle",
                parent=stylesheet["Title"],
                fontName="Helvetica-Bold",
                fontSize=22,
                leading=26,
                textColor=colors.HexColor("#0678BE"),
                spaceAfter=16,
                alignment=TA_CENTER,
            ),
            "h1": ParagraphStyle(
                "DrupalH1",
                parent=stylesheet["Heading1"],
                fontName="Helvetica-Bold",
                fontSize=20,
                leading=24,
                textColor=colors.HexColor("#0678BE"),
                spaceBefore=10,
                spaceAfter=10,
            ),
            "h2": ParagraphStyle(
                "DrupalH2",
                parent=stylesheet["Heading2"],
                fontName="Helvetica-Bold",
                fontSize=16,
                leading=20,
                textColor=colors.HexColor("#0678BE"),
                spaceBefore=10,
                spaceAfter=8,
            ),
            "h3": ParagraphStyle(
                "DrupalH3",
                parent=stylesheet["Heading3"],
                fontName="Helvetica-Bold",
                fontSize=13,
                leading=16,
                textColor=colors.HexColor("#333333"),
                spaceBefore=8,
                spaceAfter=6,
            ),
            "body": ParagraphStyle(
                "DrupalBody",
                parent=stylesheet["BodyText"],
                fontName="Helvetica",
                fontSize=10.5,
                leading=14,
                textColor=colors.HexColor("#333333"),
                spaceAfter=6,
            ),
            "bullet": ParagraphStyle(
                "DrupalBullet",
                parent=stylesheet["BodyText"],
                fontName="Helvetica",
                fontSize=10.5,
                leading=14,
                leftIndent=14,
                firstLineIndent=-8,
                spaceAfter=4,
            ),
            "code": ParagraphStyle(
                "DrupalCode",
                parent=stylesheet["Code"],
                fontName="Courier",
                fontSize=9,
                leading=11,
                backColor=colors.HexColor("#F4F4F4"),
                leftIndent=8,
                rightIndent=8,
                spaceAfter=8,
            ),
            "quote": ParagraphStyle(
                "DrupalQuote",
                parent=stylesheet["BodyText"],
                fontName="Helvetica-Oblique",
                fontSize=10,
                leading=13,
                leftIndent=16,
                borderPadding=8,
                borderColor=colors.HexColor("#0678BE"),
                borderWidth=1,
                borderLeft=True,
                textColor=colors.HexColor("#666666"),
                spaceAfter=8,
            ),
        }

        def inline_html(node: Tag) -> str:
            chunks: List[str] = []
            for child in node.children:
                if isinstance(child, NavigableString):
                    chunks.append(escape(str(child)))
                    continue
                name = child.name.lower()
                inner = inline_html(child)
                if name in {"strong", "b"}:
                    chunks.append(f"<b>{inner}</b>")
                elif name in {"em", "i"}:
                    chunks.append(f"<i>{inner}</i>")
                elif name == "code":
                    chunks.append(f"<font name='Courier'>{inner}</font>")
                elif name == "a":
                    href = escape(child.get("href", ""), quote=True)
                    chunks.append(f"<a href='{href}' color='#0678BE'>{inner}</a>")
                elif name == "br":
                    chunks.append("<br/>")
                else:
                    chunks.append(inner)
            return "".join(chunks)

        def list_item_text(li: Tag) -> str:
            parts: List[str] = []
            for child in li.children:
                if isinstance(child, NavigableString):
                    text = str(child).strip()
                    if text:
                        parts.append(escape(text))
                    continue
                if child.name and child.name.lower() in {"ul", "ol"}:
                    continue
                parts.append(inline_html(child))
            return " ".join(part for part in parts if part).strip()

        def normalize_table_cell(cell: Tag) -> str:
            text = inline_html(cell).strip()
            return text or "&nbsp;"

        def add_table(story: List[Any], table_node: Tag) -> None:
            rows = table_node.find_all("tr")
            if not rows:
                return

            data = []
            max_cols = 0
            for row in rows:
                cells = row.find_all(["th", "td"])
                max_cols = max(max_cols, len(cells))
                data.append(cells)

            if max_cols == 0:
                return

            header_style = ParagraphStyle(
                "DrupalTableHeader",
                parent=styles["body"],
                fontName="Helvetica-Bold",
                textColor=colors.white,
            )
            table_data = []
            for cells in data:
                row_data = []
                for cell in cells:
                    cell_style = header_style if cell.name.lower() == "th" else styles["body"]
                    row_data.append(Paragraph(normalize_table_cell(cell), cell_style))
                while len(row_data) < max_cols:
                    row_data.append(Paragraph("&nbsp;", styles["body"]))
                table_data.append(row_data)

            col_width = (A4[0] - (4 * cm)) / max_cols
            table = Table(table_data, colWidths=[col_width] * max_cols, repeatRows=1)
            table.setStyle(
                TableStyle(
                    [
                        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0678BE")),
                        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CCCCCC")),
                        ("VALIGN", (0, 0), (-1, -1), "TOP"),
                        ("LEFTPADDING", (0, 0), (-1, -1), 6),
                        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                        ("TOPPADDING", (0, 0), (-1, -1), 4),
                        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                        (
                            "ROWBACKGROUNDS",
                            (0, 1),
                            (-1, -1),
                            [colors.white, colors.HexColor("#F9F9F9")],
                        ),
                    ]
                )
            )
            story.append(table)
            story.append(Spacer(1, 10))

        soup = BeautifulSoup(html_body, "html.parser")
        story: List[Any] = [Paragraph(escape(doc_title), styles["title"]), Spacer(1, 8)]

        for node in soup.contents:
            if isinstance(node, NavigableString):
                continue

            name = node.name.lower()
            if name == "h1":
                story.append(Paragraph(inline_html(node), styles["h1"]))
            elif name == "h2":
                story.append(Paragraph(inline_html(node), styles["h2"]))
            elif name in {"h3", "h4", "h5", "h6"}:
                story.append(Paragraph(inline_html(node), styles["h3"]))
            elif name == "p":
                story.append(Paragraph(inline_html(node), styles["body"]))
            elif name in {"ul", "ol"}:
                bullet_char = "•" if name == "ul" else None
                for index, li in enumerate(node.find_all("li", recursive=False), start=1):
                    prefix = bullet_char or f"{index}."
                    story.append(Paragraph(f"{prefix} {list_item_text(li)}", styles["bullet"]))
            elif name == "pre":
                code_node = node.find("code")
                code_text = code_node.get_text("\n") if code_node else node.get_text("\n")
                story.append(Preformatted(code_text.rstrip(), styles["code"]))
            elif name == "blockquote":
                story.append(Paragraph(inline_html(node), styles["quote"]))
            elif name == "table":
                add_table(story, node)
            elif name == "hr":
                story.append(Spacer(1, 6))

        def add_page_number(canvas, doc):
            canvas.setFont("Helvetica", 9)
            canvas.setFillColor(colors.HexColor("#666666"))
            canvas.drawCentredString(A4[0] / 2, 1.2 * cm, f"Page {doc.page}")

        doc = SimpleDocTemplate(
            str(pdf_path),
            pagesize=A4,
            leftMargin=2 * cm,
            rightMargin=2 * cm,
            topMargin=2 * cm,
            bottomMargin=2 * cm,
            title=doc_title,
        )
        doc.build(story, onFirstPage=add_page_number, onLaterPages=add_page_number)
        return True, None
    except Exception as e:
        message = str(e)
        print(f"PDF generation failed: {message}")
        return False, message


def append_pdf_failure_notice(markdown_path: Path, message: str) -> None:
    """Append a single PDF failure note to summary markdown."""
    if not markdown_path.exists() or not message:
        return

    notice_header = "## PDF Generation Notice"
    if notice_header in markdown_path.read_text(encoding="utf-8"):
        return

    notice = (
        "\n\n---\n\n"
        f"{notice_header}\n\n"
        "`summary.pdf` was not generated.\n\n"
        f"Reason: {message}\n"
    )
    with markdown_path.open("a", encoding="utf-8") as handle:
        handle.write(notice)


def generate_summary_pdf(
    run_dir: Path,
    markdown_filename: str = "summary.md",
    pdf_filename: str = "summary.pdf",
    period_label: str = "Weekly",
) -> Tuple[Optional[Path], Optional[str]]:
    """Generate PDF from summary markdown in run directory."""
    markdown_path = run_dir / markdown_filename
    pdf_path = run_dir / pdf_filename

    if not markdown_path.exists():
        message = f"Markdown file not found: {markdown_path}"
        print(f"Error: {message}")
        return None, message

    title = f"Drupal {period_label} Summary - {run_dir.name}"
    ok, message = markdown_to_pdf(markdown_path, pdf_path, title=title)
    if ok:
        return pdf_path, None
    return None, message
